/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pr.corina.lab2pr;

import com.pr.corina.lab2pr.entities.Category;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JScrollPane;
import javax.swing.JTree;
import javax.swing.SwingWorker;
import javax.swing.tree.DefaultMutableTreeNode;
import static org.apache.http.client.methods.RequestBuilder.get;

/**
 *
 * @author corina
 */
public class AppFrame extends javax.swing.JFrame {
    
    private JTree jTree;
    private JScrollPane jScrollPane;

    /**
     * Creates new form AppFrame
     */
    public AppFrame() {
        
        initComponents();
        myInitComponents();

    }

    public void myInitComponents() {
        App.initApp("2018-01-01", "2018-03-01", Boolean.FALSE);
        initTree();
        jFormattedFieldFrom.setText("2018-01-01");
        jFormattedFieldTo.setText("2018-03-01");
    }

    public void initTree(){
           
           DefaultMutableTreeNode baseNode = new DefaultMutableTreeNode("All Categories Data");
           loadTreeNodes(baseNode, App.getCategoryList());
           jTree=new JTree(baseNode);
           jScrollPane=new JScrollPane();
           jScrollPane.setViewportView(jTree);
           jScrollPane.setBounds(70, 110, 720, 400);
           jTree.setSize(720,400);
           jTree.setVisible(Boolean.TRUE);
           
           add(jScrollPane);
            
    }

    public void reloadTree(){
           DefaultMutableTreeNode baseNode = new DefaultMutableTreeNode("All Categories Data");
           loadTreeNodes(baseNode, App.getCategoryList());
           jTree=new JTree(baseNode);
           jScrollPane.setViewportView(jTree);
           jTree.setSize(720,400);
           jTree.setVisible(Boolean.TRUE);
           jScrollPane.repaint();
    }
    
    
    
    public void loadTreeNodes(DefaultMutableTreeNode baseNode, List<Category>categoryList){
         for(Category category:categoryList){
             System.out.println("Category_id="+category.getId());
              DefaultMutableTreeNode defaultNode = new DefaultMutableTreeNode(category.getId()+"."+category.getName()+"-"+category.getTotal());
              baseNode.add(defaultNode);
              if(!category.getCategoryList().isEmpty())
                  loadTreeNodes(defaultNode, category.getCategoryList());
         }
    }
    
 

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBtnGenerate = new javax.swing.JToggleButton();
        jFormattedFieldFrom = new javax.swing.JFormattedTextField();
        jFormattedFieldTo = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("UnBatang", 1, 18)); // NOI18N
        jLabel1.setText("Total by categories");

        jLabel2.setFont(new java.awt.Font("UnBatang", 1, 15)); // NOI18N
        jLabel2.setText("From");

        jLabel3.setFont(new java.awt.Font("UnBatang", 1, 15)); // NOI18N
        jLabel3.setText("To");

        jBtnGenerate.setText("Generate");
        jBtnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGenerateActionPerformed(evt);
            }
        });

        jFormattedFieldFrom.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        jFormattedFieldFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedFieldFromActionPerformed(evt);
            }
        });

        jFormattedFieldTo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        jPanel1.setBackground(new java.awt.Color(251, 247, 243));

        jLabel4.setFont(new java.awt.Font("UnBatang", 1, 20)); // NOI18N
        jLabel4.setText("Evil App - Reports");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedFieldFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedFieldTo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jBtnGenerate)
                    .addComponent(jFormattedFieldFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedFieldTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(420, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGenerateActionPerformed
        
    SwingWorker worker = new SwingWorker() {
    @Override
    public Integer doInBackground() {
        
       System.out.println("===== Generation Start======");
        System.out.println("**"+javax.swing.SwingUtilities.isEventDispatchThread());
        // 1. Get Dates From jFormatterFields
        String dateFrom=jFormattedFieldFrom.getText();
        String dateTo=jFormattedFieldTo.getText();
          System.out.println("Date From:"+dateFrom);
          System.out.println("Date To:"+dateTo);
        // 2. Get Method        
        App.initApp(dateFrom, dateTo,  Boolean.TRUE);
        // 3. Load Tree
        reloadTree();
        publish("Work is done!");
        return 1;
    } 

    @Override
    public void done() {
        System.out.println("==== Generation is Done====");
        repaint();
        revalidate();
    }
    }; 
           worker.execute();
    }//GEN-LAST:event_jBtnGenerateActionPerformed

    
    private void jFormattedFieldFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedFieldFromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedFieldFromActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jBtnGenerate;
    private javax.swing.JFormattedTextField jFormattedFieldFrom;
    private javax.swing.JFormattedTextField jFormattedFieldTo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
